# Generated by Django 3.0.4 on 2020-03-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localusers', '0004_auto_20200310_1649'),
        ('posts', '0002_auto_20200312_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disco_server', to='localusers.DiscoServer'),
        ),
    ]
