# Generated by Django 3.0.4 on 2020-03-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localusers', '0003_auto_20200310_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uid', models.TextField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='discoserver',
            name='uid',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='membership',
            name='subbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoserver',
            name='channels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localusers.DiscoChannel'),
        ),
    ]
